name: pie_menu
description: A Flutter library that provides a customizable circular/radial context menu.
version: 0.2.0
homepage: https://github.com/RasitAyaz/flutter-pie-menu

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: